case actionTypes.START_UPDATING_UNSOLD_INVENTORY:

case actionTypes.UPDATE_INVESTMENTS_LINES
    
case actionTypes.START_UPDATING_SCREEN:
   
case actionTypes.START_APPLYING_PROFIT_LOSS:

case actionTypes.START_COUNTING_RISK:
    
case actionTypes.START_ADDING_EMPTY_INVESTMENTS_LINE:

        
    
    START_NEW_TOURNAMENT
    START_RUNNING_STRATEGIC_MODELING
    UPDATE_STRATEGIC_MODELING_ROUND

    STOP_TOURNAMENT

  TOURNAMENT_STARTED
  TOURNAMENT_DURATION
  
    actions test updated(UPDATE_INVESTMENTS_DELAY)


    

    
