export {
    checkButtons,
    makePaperclip,
    sellPaperclips,
    updateFunds,
    startUpdatingUnsoldInventory,
    updateUnsoldInventory,
    lowerPrice,
    raisePrice,
    updatePublicDemand,
    toggleMarketingButton,
    marketing,
    marketingNextLevel,
    updateMaxPublicDemand,
    buyWire,
    randomWirePrice,
    toggleWireButton,
    checkExistenceOfWire,
    stop,
    startBuyingWire,
    autoPaperclips,
    autoPaperclipsStart,
    autoClippersAddOne,
    setAutoClipperInitPrice,
    toggleAutoClippersButton,
    toggleMegaClippersButton,
    trustPlusOne,
    increaseOps,
    startDecreasingOps,
    stopDecreasingOps,
    decreaseOps,
    increaseProcessors,
    increaseProcessorsMemory,
    increaseCreativity,
    initProjects,
    checkCardValidity,
    deleteCard,
    showRevTracker,
    addProject,
    removePriceOfProjectOps,
    removePriceOfProjectCreat,
    removePriceOfProjectOpsAndCreat,
    removePriceOfProjectTrust,
    improveAutoClippers, 
    toggleMakePaperclipButton,
    improveWireExtrusion,
    // startCreativityCounter,
    creativityTurnOn,
    trustPlusOneFromProject,
    wireExists,
    // addLexicalProcessing,
    // addCombinatoryHarmonics,
    // addTheHadwingerProblem,
    // addTheTothSausageConjecture,
    // addDonkeySpace,
    improveMarketing,
    showInvestEngine,
    showStrategicModeling,
    sendCommentToTerminal,
    addNewStrategy,
    toggleDropdownInvestments,
    toggleDropdownStrategicModeling,
    closeDropdowns,
    showQuantCompMessage,
    showQuantumComputing,
    changeToQOps,
    startAddingQOps,
    addQOps,
    stopAddingQOps,
    startSubtractingQOps,
    subtractQOps,
    stopSubtractingQOps,
    captureCurrentQOps,
    addChip,
    toggleChip,
    updateOps,
    startDecreasingOperations,
    startTimer,
    clickWireButton,
    showAutoWireBuyer,
    toggleWireBuyerProject,
    autoWireBuyer,
    toggleAutoWireBuyer,
    addMegaClippers,
    showMegaClippers,
    showAutoClippers,
    calcDelayUnsoldInventary,
    stopUpdatingUnsoldInventory,
    startImprovingMarketing,
    updateClipsPerSec,
    startInvestmentsDeposit,
    getDeposit,
    startUpdatingScreen,
    stopUpdatingScreen,
    addInvestmentsLine,
    startUpdatingInvestmentLines,
    stopUpdatingInvestmentLines,
    updateInvestmentsLines,
    startCountingRisk,
    updateInvestmentsTotal,
    updateInvestmentsCash,
    updateInvestmentsStocks,
    startApplyingProfitLoss,
    updateFakeInvestmentsCash,
    startInvestmentsWithdraw,
    updateFundsWithdraw,
    chooseFromDropdown,
    addChosenFromDropdown,
    updateInvestmentsDelay,
    startAddingEmptyInvestmentsLine,
    stopAddingEmptyInvestmentsLine,
    updateAvgRevPerSec,
    updateAvgClipsSoldPerSec,
    megaClippersButtonPressed,
    startMegaClippers,
    improveMegaClippers,
    switchOffOrOnAutoAndMegaClippers,
    startNewTournament,
    tournamentState,
    updateNewTournamentCost,
    toggleNewTournamentButton,
    startRunningStrategicModeling,
    updateStrategicModelingData,
    updateStrategicModelingCurrentList,
    strategyChosen,
    clearChosenFromStrategicModelingDropdownList,
    updateStrategicModelingRound,
    tournamentStarted,
    stopTournament,
    tournamentDuration,
    // updateNumberOfRounds,
    showRoundAndPlayers,
    startUpdatingRoundsOnScreen,
    updateRoundsOnScreen,
    startUpdatingPlayerLeftOnScreen,
    updatePlayerLeftOnScreen,
    startUpdatingPlayerTopOnScreen,
    updatePlayerTopOnScreen,
    setPlayersArrays,
    gameStarted,
    allRoundsResult,
    startCountingResult,
    updatedAllRoundsRes,
    strategicModelingResult,
    countFinalResultOfEachStrategy,
    updateListOfFinalResult,
    fillWithValuesStrategicModelingCurrentList,
    toggleStrategicModelingLeftPart,
    toggleStrategicModelingHover,
    toggleCells,
    updateYomi,
    // addCoherentExtrapolatedVolition,
    removePriceOfProjectOpsCreatAndYomi,
    removePriceOfProjectOpsAndYomi,
    removePriceOfProjectYomiAndMoney,
    removePriceOfProjectMoney,
    // addXavierReinitialization,
    reallocationOfTrust,
    // addHostileTakeover,
    upgradeInvestmentEngine,
    stateFromLocalStorage,
    toggleThrownProject,
    removeUnnecessaryCards,
    showManufacturingSection,
    updateWire,
    showBusinessSection,
    showProcessorsNumber,
    showProcessorsMemory,
    showWirePart,
    lastComents,
    stopSendingLastComments,
    stopComments
    // toggleThrownProjectStartCreativityCounter,
    // toggleThrownProjectLexicalProcessing,
    // toggleThrownProjectCombinatoryHarmonics,
    // toggleThrownProjectTheHadwingerProblem,
    // toggleThrownProjectTheTothSausageConjecture,
    // toggleThrownProjectDonkeySpace,
    // toggleThrownProjectXavierReinitialization,
    // toggleThrownProjectHostileTakeover,
    // toggleThrownProjectQuantumComputing,
    // toggleThrownProjectCoherentExtrapolatedVolition,
    // toggleThrownProjectQuantumTemporalReversion
} from './businessActions';
