export const MOVE_CIRCLE_X_COORDINATE = 'MOVE_CIRCLE_X_COORDINATE';
export const MOVE_CIRCLE_Y_COORDINATE = 'MOVE_CIRCLE_Y_COORDINATE';
export const CHANGE_DIRECTION_OF_X_MOVE = 'CHANGE_DIRECTION_OF_X_MOVE';
export const CHANGE_DIRECTION_OF_Y_MOVE = 'CHANGE_DIRECTION_OF_Y_MOVE';
export const UPDATE_COORDINATES = 'UPDATE_COORDINATES';
export const UPDATE_VELOCITIES = 'UPDATE_VELOCITIES';

export const ADD_CHIP = 'ADD_CHIP';


