export const MOVE_CIRCLE_X_COORDINATE = 'MOVE_CIRCLE_X_COORDINATE';
export const MOVE_CIRCLE_Y_COORDINATE = 'MOVE_CIRCLE_Y_COORDINATE';
export const CHANGE_DIRECTION_OF_X_MOVE = 'CHANGE_DIRECTION_OF_X_MOVE';
export const CHANGE_DIRECTION_OF_Y_MOVE = 'CHANGE_DIRECTION_OF_Y_MOVE';
export const UPDATE_COORDINATES = 'UPDATE_COORDINATES';
export const UPDATE_VELOCITIES = 'UPDATE_VELOCITIES';
export const FILL_CIRCLES_ARRAY = 'FILL_CIRCLES_ARRAY';
export const UPDATE_CIRCLES_ARRAY = 'UPDATE_CIRCLES_ARRAY';
export const GET_NUMBERS_OF_BALLS = 'GET_NUMBERS_OF_BALLS';

export const MOUSE_DOWN = 'MOUSE_DOWN';
export const GET_COLOR = 'GET_COLOR';
export const CAPTURE_LAST_X_Y = 'CAPTURE_LAST_X_Y';
export const CAPTURE_X_Y = 'CAPTURE_X_Y';

export const ADD_CHIP = 'ADD_CHIP';


