export const MAKE_PAPERCLIP = 'MAKE_PAPERCLIP';

export const START_SELLING = 'START_SELLING';
export const UPDATE_FUNDS = 'UPDATE_FUNDS';
export const UPDATE_UNSOLD_INVENTORY = 'UPDATE_UNSOLD_INVENTORY';

export const LOWER_PRICE = 'LOWER_PRICE';
export const RAISE_PRICE = 'RAISE_PRICE';

export const UPDATE_PUBLIC_DEMAND = 'UPDATE_PUBLIC_DEMAND';
export const MARKETING = 'MARKETING';
export const TOGGLE_MARKETING_BUTTON = 'TOGGLE_MARKETING_BUTTON';
export const MARKETING_NEXT_LEVEL = 'MARKETING_NEXT_LEVEL';
export const UPDATE_MAX_PUBLIC_DEMAND = 'UPDATE_MAX_PUBLIC_DEMAND';


export const BUY_WIRE = 'BUY_WIRE';
export const RANDOM_WIRE_PRICE = 'RANDOM_WIRE_PRICE';
export const WIRE_PRICE = 'WIRE_PRICE';






